language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t bluckose/docker-react -f Dockerfile.dev .

script:
    - docker run bluckose/docker-react npm run test -- --coverage